# Site settings
title: Yu-Cheng Qiu | Ph.D in Physics
description: "This is a site sharing knowledge of physics. Please contact me if you have any inquiry."
url: "https://ethan-phys.github.io"
author:
  name: "Yu-Cheng Qiu"
  email: "ethan.qiu@cityu.edu.hk"
  url: "https://ethan-phys.github.io"

# Build settings
baseurl: "" # Leave empty for a root-site deployment
markdown: kramdown
source: .
destination: ./_site
permalink: /:title.html
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

collections:
   publications:
      output: true
      
